### ISSUE TITLE
:lady_beetle: [BUG] Crash logs for 4.0.8-alpha

### ISSUE THREAD

**Issue by AeliusSaionji** [octoshrimpy/quik#176] opened 2024-11-02 14:45 UTC
Android 14

Crash log after updating to 4.0.8-alpha, resolved by clearing appdata.

```log
FATAL EXCEPTION: main
Process: dev.octoshrimpy.quik, PID: 8287
java.lang.RuntimeException: Failed to find the generated JsonAdapter class for class dev.octoshrimpy.quik.manager.ChangelogManagerImpl$Changeset
	at com.squareup.moshi.internal.Util.generatedAdapter(Unknown Source:231)
	at com.squareup.moshi.StandardJsonAdapters$1.create(Unknown Source:145)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(Unknown Source:6)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(Unknown Source:35)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at dev.octoshrimpy.quik.manager.ChangelogManagerImpl.getChangelog(Unknown Source:16)
	at dev.octoshrimpy.quik.feature.main.MainViewModel$bindView$18.invokeSuspend(Unknown Source:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:95)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: java.lang.ClassNotFoundException: dev.octoshrimpy.quik.manager.ChangelogManagerImpl_ChangesetJsonAdapter
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at com.squareup.moshi.internal.Util.generatedAdapter(Unknown Source:52)
	... 21 more
Caused by: java.lang.ClassNotFoundException: dev.octoshrimpy.quik.manager.ChangelogManagerImpl_ChangesetJsonAdapter
	... 24 more
```
----
Crash log on first run during sms db sync. No further crashes, though 🤔

```log
FATAL EXCEPTION: main
Process: dev.octoshrimpy.quik, PID: 15682
java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: QkViewHolder{f1e25ab position=11 id=83, oldPos=-1, pLpos:-1 update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{ba96572 VFED..... ........ 0,140-1080,2217 #7f0a017a app:id/recyclerView}, adapter:dev.octoshrimpy.quik.feature.conversations.ConversationsAdapter@a69230d, layout:androidx.recyclerview.widget.LinearLayoutManager@8012c2, context:dev.octoshrimpy.quik.feature.main.MainActivity@a93cc70
	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(Unknown Source:229)
	at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(Unknown Source:22)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(Unknown Source:27)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(Unknown Source:7)
	at androidx.recyclerview.widget.SimpleItemAnimator.dispatchAddFinished(Unknown Source:3)
	at androidx.recyclerview.widget.DefaultItemAnimator$5.onAnimationEnd(Unknown Source:10)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:708)
	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at android.animation.Animator.callOnList(Animator.java:666)
	at android.animation.Animator.notifyListeners(Animator.java:609)
	at android.animation.Animator.notifyEndListeners(Animator.java:634)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1566)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1363)
	at android.view.Choreographer.doCallbacks(Choreographer.java:963)
	at android.view.Choreographer.doFrame(Choreographer.java:888)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1337)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
```

**Comment by octoshrimpy** [comment] 2024-11-05 04:11
dupe of #175 , fixed with https://github.com/octoshrimpy/quik/releases/tag/v4.0.8-beta

**Closed by octoshrimpy** 2024-11-05 04:11 UTC
Labels: bug
