### ISSUE TITLE
✏️ [ FEAT REQ ] e2ee support

### ISSUE THREAD

**Issue by GregTechSexHorizons** [octoshrimpy/quik#82] opened 2024-03-11 02:37 UTC
It would be nice to have e2ee support like silence or deku sms. Silence is abandoned for 5 years and deku sms does not support mms.

Im pretty sure what silence did was just copy paste signals protocol and use it over sms/mms. Maybe it will be easy to implement if you do the same thing?

**Comment by Dyras** [comment] 2024-03-11 20:38
Duplicate of https://github.com/octoshrimpy/quik/issues/55

**Closed** 2024-03-12 01:41 UTC
Labels: enhancement
